- README.md
初期設定手順のネットワーク名を修正したので確認をお願いいたします。
> #9 初期設定のネットワーク名を修正

- api/app/controllers/api/v1/sessions_controller.rb
- api/config/routes.rb
- api/test/controllers/api/v1/sessions_controller_test.rb
https://github.com/e-harp-intern/R4FY/wiki/login
https://github.com/e-harp-intern/R4FY/wiki/logout
- ログイン、ログアウトができること
> ログインAPIの実装

- README.md
説明と`seed.rb`の初期値が違ったので説明側を修正しました。
> 初期アカウント情報説明の修正

- web/src/components/SideMenu.vue
- web/src/i18n/languages/ja.js
- web/src/router/index.js
- web/src/views/TourView.vue
ツアー詳細確認画面を追加しました。
現在はメニューバーからの遷移になっていますが、ツアー一覧からツアーを選択した際の遷移先になる予定だと思います
> ツアー詳細確認画面追加

- api/app/controllers/api/v1/tourdetail_controller.rb
- api/app/controllers/api/v1/toursort_controller.rb
- api/config/routes.rb
https://github.com/e-harp-intern/R4FY/wiki/tourdetail
- ツアー詳細の取得ができること
> #12 ツアー詳細取得APIの作成

- web/.eslintrc.json
- web/src/components/SideMenu.vue
- web/src/i18n/languages/ja.js
- web/src/router/index.js
- web/src/views/ToursListView.vue
API実装
ツアー一覧画面のテーブル実装（ソート、ホバー、リンク）
ツアー一覧画面の日本語をja.jsに移動
> ツアー一覧確認画面機能追加

- api/app/controllers/api/v1/admins_controller.rb
- api/app/controllers/api/v1/guides_controller.rb
- api/app/controllers/api/v1/toursort_controller.rb
- api/app/controllers/concerns/common.rb
- api/config/routes.rb
https://github.com/e-harp-intern/R4FY/wiki/admins
https://github.com/e-harp-intern/R4FY/wiki/guides
- 管理者,ガイドのアカウント作成ができること
> #15 アカウント作成APIの作成 

- api/app/controllers/api/v1/tourdetail_controller.rb
- api/db/migrate/20220829041827_create_emails.rb
- api/db/migrate/20220829043230_create_guide_schedules.rb
- api/db/migrate/20220829044434_create_tour_guides.rb
- api/db/migrate/20220829044654_create_tokens.rb
- api/db/migrate/20220829044824_create_password_reset_tokens.rb
- api/db/migrate/20220831051238_rename_achievement_column_to_tour_guides.rb
- api/db/schema.rb
- api/db/seeds.rb
> #12 ツアー詳細取得APIの作成の修正

- web/src/components/SideMenu.vue
- web/src/i18n/languages/ja.js
- web/src/router/index.js
- web/src/views/CreateTour.vue
- web/src/views/ToursListView.vue
> #17 ツアー新規追加画面　作成

- api/app/controllers/api/v1/touradds_controller.rb
- api/config/routes.rb
https://github.com/e-harp-intern/R4FY/wiki/touradds
- ツアー予定の追加ができること
> #18 ツアー予定追加機能の作成

- api/app/controllers/api/v1/touradds_controller.rb
- api/db/migrate/20220901053327_rename_adalt_num_column_to_tours.rb
- api/db/schema.rb
> #45 DBのツアー詳細のadalt_numをadult_numに修正

- web/src/views/CreateTour.vue
API、機能の実装完了しました
adultがadaltになっています、変更お願いします
> #19 ツアー予定作成機能実装しました

- .gitignore
- api/Gemfile
- api/Gemfile.lock
- api/config/cronotab.rb
- api/config/initializers/mail.rb
- api/config/mail.yml
- api/db/migrate/20220901075337_create_crono_jobs.rb
- api/db/schema.rb
- api/env.tmp
- docker-compose.yml
> #48 メール及びバッチ処理設定の修正

- api/app/controllers/api/v1/tourdetail_controller.rb
- api/app/controllers/concerns/common.rb
- api/config/routes.rb
- api/db/seeds.rb
> #21 ツアー中止APIを作成

- api/app/models/email.rb
- api/app/models/guide.rb
- api/app/models/guide_schedule.rb
- api/app/models/password_reset_token.rb
- api/app/models/token.rb
- api/app/models/tour.rb
- api/app/models/tour_guide.rb
> #60 Active Recordの関連付け（アソシエーション）

- api/db/seeds.rb
> #42 テスト用データ追加

- api/db/seeds.rb
> #79 → #20 DB初期データの修正

- docker-compose.yml
Dockerfile修正しています。バッチ処理のコマンドを壊していないか、時間がある時に確認をお願いします。
> #63 サーバー起動時にpidファイルを削除するように修正

- docker-compose.yml
> #84 pidファイルがない場合でも起動できるように修正

- web/.eslintrc.json
- web/src/assets/css/style.css
- web/src/i18n/languages/ja.js
- web/src/mixins/common.js
- web/src/mixins/table.js
- web/src/views/TourView.vue
> #20 ツアー取り消しボタンを追加

- api/app/controllers/api/v1/tour_controller.rb
- api/app/controllers/api/v1/tours_controller.rb
- api/app/controllers/api/v1/toursort_controller.rb
- api/config/routes.rb
- web/src/components/SideMenu.vue
- web/src/mixins/common.js
- web/src/views/TourView.vue
- web/src/views/ToursListView.vue
> #44 処理の共通化と統一

- api/app/controllers/application_controller.rb
> #59 エラー時の形を変更

- api/app/controllers/api/v1/admins_controller.rb
- api/app/controllers/api/v1/guides_controller.rb
- api/app/controllers/api/v1/sessions_controller.rb
- api/app/controllers/api/v1/tour_controller.rb
- api/app/controllers/api/v1/tours_controller.rb
- api/app/controllers/application_controller.rb
Postman等で試す場合も、一度ログインしてからでなければデータを取得することができなくなるので注意。
> #23 ログイン認証機能を有効化

- api/app/controllers/api/v1/tours_controller.rb
> #97 ツアー追加からトランザクション処理を削除

- api/db/seeds.rb
管理者テストデータの追加とツアー状態コードの変更をしています。
- [ER図 - 状態コードの説明](https://github.com/e-harp-intern/R4FY-docs/blob/main/13-ER%E5%9B%B3.drawio.svg)
- 正しく初期データが反映されること。
> #99 テストデータの追加・変更

- .gitignore
- api/app/controllers/front_controller.rb
- api/config/routes.rb
- build.sh
- ログインしてないときにログインページへリダイレクトすること
> #7 検証環境用の設定等を追加

- web/src/views/LoginView.vue
- LoginViewのtourslistだった部分をtoursに変更
- ブラウザで実際に画面遷移したことを確認
> #82 ログイン時にtourslistではなくtoursに遷移するよう変更

- api/app/controllers/api/v1/admins_controller.rb
- api/config/routes.rb
管理者名表示のAPIの作成
- 管理者がログインしたら、管理者の登録データが確認できること
- 管理者がログインしていなければ、エラーとなること
> #96 管理者名取得のAPI

- .githooks/pre-commit
- api/.rubocop.yml
- api/app/controllers/api/v1/accounts_controller.rb
- api/app/controllers/api/v1/sessions_controller.rb
- api/app/controllers/api/v1/tour_guides_controller.rb
- api/app/controllers/api/v1/tours_controller.rb
- api/db/seeds.rb
再度 `git config --local core.hooksPath .githooks` を行なう必要があります。
> #141 オートフォーマットの修正

- api/app/controllers/api/v1/tours_controller.rb
- ツアーの作成にトランザクション処理を追加
- DB Browserを用いて確認
> #142 ツアー作成のトランザクションを追加

- api/app/controllers/api/v1/admins_controller.rb
- api/app/controllers/api/v1/guides_controller.rb
- api/config/routes.rb
- guidesとadminsに論理削除を行うメソッドを追加しました
- DB Browserで実際に削除フラグが1になったか確認しました
> #111 guidesとadminsの論理削除

- api/db/migrate/20220907003002_tour_templates_datetime_to_null.rb
- api/db/schema.rb
- api/db/seeds.rb
- ダミーデータを追加しました
- DB Browserでダミーデータがあることを確認しました
> #112 ツアーテンプレートのダミーデータ作成途中

- web/src/i18n/languages/ja.js
- web/src/views/ToursListView.vue
- 現在ログインしている管理者の名前を表示する。
- ログインすると、例えば「管理者さん、こんにちは！」と表示される。
> #100 現在ログインしている管理者の名前を表示する

- api/app/models/application_record.rb
- API「管理者の自分自身の情報を取得する」のpassword_digestを取り除く
- 管理者情報に登録されているpassword_digestが取り除かれた
> #145　API「管理者の自分自身の情報を取得する」のpassword_digestを取り除く

- web/src/views/AccountView.vue
> #157　タグの変更

- api/db/seeds.rb
- web/src/i18n/languages/ja.js
- web/src/views/ToursListView.vue
表示するデータが無い場合のメッセージを追加しました。テストデータも追加しています。
時間がある時に確認をお願いいたします。
- ツアー一覧データが無い場合に、メッセージを表示されること
- ツアー一覧デーがある場合に、メッセージが表示されないこと
> #163 ツアー一覧に表示するデータが無い場合の表示を追加

- api/app/controllers/api/v1/guides_controller.rb
- api/config/routes.rb
- ガイド情報・ツアー情報をトークンを参照して取得できるようにしました
- Postmanで条件通りの出力になることを確認
> #72 ガイド情報・ツアー情報の取得

- api/app/controllers/api/v1/guides_controller.rb
- api/config/routes.rb
- トークンを利用してガイドスケジュール(true/false)をDBに反映されるようにしました
- DB Browserで反映されたことを確認しました
> #73 ガイドスケジュールをDBに反映

- api/app/controllers/api/v1/guides_controller.rb
- api/config/routes.rb
- ガイド情報・関連したツアー情報だけでなく入力済の参加可否情報も表示できるよう変更
- Postmanで出力を確認
> #104 ガイドが入力済のガイド情報・関連したツアー情報・入力済の参加可否情報を表示する機能

- api/app/controllers/api/v1/templates_controller.rb
- api/app/controllers/api/v1/tours_controller.rb
- api/config/routes.rb
- 指定したIDのツアーテンプレートを表示する機能を追加。URLは` localhost:3000/api/v1/tours/:id/templates `とした。
- postmanで出力を確認
> #127 ツアーテンプレートの取得

- web/src/App.vue
- web/src/components/LoadingTemplate.vue
- web/src/components/layout/DefaultLayout.vue
後ろに表示されるように設定されていたので、最前面に来るように修正。アニメーションの位置を全画面で固定になるように修正しました。
> #88 ロードアニメーションが最前面に表示されるよう修正

- web/src/views/ToursListView.vue
> #183 ツアー一覧でツアー状態によってセルに色が付くよう変更

- docs/初回起動手順.md
> #189 初回起動手順のメールの設定ファイルの場所が間違っていたので修正

- web/src/views/AccountView.vue
> #188 アカウント作成ボタンのリンク先アドレスが間違っていたので修正

- api/config/routes.rb
- web/src/views/guide/InputSchedule.vue
パスのみ変更しています。フロントの呼び出し側、Wikiも更新しています。
> #192 スケジュール関連のAPIのパスを統一

- web/src/components/LoadingTemplate.vue
- web/src/components/SideMenu.vue
- web/src/components/layout/DefaultLayout.vue
- web/src/views/AccountView.vue
- web/src/views/ToursListView.vue
サイドバークリックで開くページは読み込み時にアニメーションを止めるようにする。
> #207 サイドバークリック時にロードアニメーションを有効化

- api/app/controllers/front_controller.rb
- api/config/routes.rb
APIアクセス時に、JSONで404エラーが返るようにした。
> #203 APIのパスが間違っている場合のエラーを定義

- web/src/mixins/api.js
- web/src/views/AccountView.vue
- web/src/views/TourView.vue
- web/src/views/ToursListView.vue
- web/src/views/guide/InputSchedule.vue
> #211 GETのURLパラメータの組み立てをmixin内に移動

- api/app/controllers/api/v1/tours_controller.rb
> #214 ツアー一覧のデフォルト値を変更

- web/src/components/SideMenu.vue
- web/vue.config.js
> #216 タイトル周りの編集

- web/src/components/SideMenu.vue
- web/src/i18n/languages/ja.js
- web/src/router/index.js
- web/src/views/LogoutView.vue
> #197 ログアウト機能の作成

- api/app/controllers/concerns/common.rb
- api/env.tmp
> #210 メール用のURL文字列をenvに移動

- web/src/mixins/api.js
> #246 GETリクエストで不要なURLパラメータがつかないように修正

- web/src/views/ToursListView.vue
> #247 ツアー一覧画面でデータ取得部分を並列化

- api/app/controllers/api/v1/guides_controller.rb
- api/config/routes.rb
- 正しく取得できること
- 論理削除済みの場合はエラーを返すこと
> #239 ガイドの詳細を取得するAPIを作成

- web/src/i18n/languages/ja.js
- web/src/views/CreateAccount.vue
> #235 アカウント作成画面にキャンセルボタンを配置

- web/src/assets/css/style.css
> #256 ボタンデザインの変更

- api/app/controllers/front_controller.rb
> #240 フロントコントローラーで404エラーを返すことができるように修正

- api/app/controllers/api/v1/sessions_controller.rb
- 削除済みの管理者でログインした際、エラーを吐くよう変更
- postmanで動作を確認
> #218 削除済みの管理者がログインできないよう変更

- web/src/views/ToursListView.vue
> #261 ツアー一覧画面で担当者決定済みの色が間違っている問題を修正

- web/src/assets/css/table.scss
- web/src/views/AccountView.vue
- web/src/views/SelectGuide.vue
- web/src/views/TourView.vue
- web/src/views/ToursListView.vue
ツアー一覧のデザインで統一しています。
- すべての画面で同じデザインのテーブルが使用されること。
> #243 テーブルCSSの共通化

- docs/検証環境手順.md
> #272 検証環境の手順をまとめました

- api/app/controllers/api/v1/template_controller.rb
- api/app/controllers/api/v1/templates_controller.rb
- api/config/routes.rb
- ツアーテンプレートの一覧を表示する機能を作成
- https://github.com/e-harp-intern/R4FY/wiki/templates-index
- postmanで確認
> #114 ツアーテンプレートの一覧を取得

- api/app/controllers/api/v1/tours_controller.rb
- api/config/routes.rb
- ガイドの参加可否情報を変更できるよう変更
- https://github.com/e-harp-intern/R4FY/wiki/tours-update
- postmanで確認
> #125 管理者側でガイドの参加可否情報を変更

- api/app/controllers/application_controller.rb
フロント側はそもそもHTTPのエラーコードを見ていました。使っていないコードですが、一応修正しておきます。
- 認証エラーで 401 が返ること。
> #268 認証エラーのエラーコードを401に変更

- web/src/views/ToursListView.vue
仕様変更に伴う変更です。
- ツアー一覧画面で正しく管理者名が表示できること。
> #273 管理者情報取得APIの仕様が変わったのでフロント側の受け取り部分を修正

- api/app/controllers/api/v1/admins_controller.rb
- パスワード変更機能を追加
- 管理者としてログインしていない場合、編集できないよう設定
- ほかの管理者の編集をできないよう変更
- wikiを修正→https://github.com/e-harp-intern/R4FY/wiki/admins-update
- postmanとDBを確認
> #266 パスワード変更機能など

- web/src/assets/css/style.css
- web/src/i18n/languages/ja.js
- web/src/router/index.js
- web/src/views/AccountView.vue
- web/src/views/accounts/GuideDetail.vue
> #124 ガイドの詳細情報を表示するページを作成

- web/src/views/AccountView.vue
> #288 管理者詳細ページは作らないことにしたのでリンクを無効化

- web/src/assets/css/style.css
- web/src/assets/css/table.scss
- web/src/views/AccountsListView.vue
管理者タブとガイドタブで表示を切り替えることができるようにしました。
> #287 アカウント一覧画面でガイドと管理者の表示を切り替えるタブを設置

- api/app/controllers/api/v1/achievements_controller.rb
- ツアー状態が更新されないバグを修正
- postmanとDBを確認
> #226 ツアー実績状態がすべて記入済みであればツアー状態を更新する

- api/app/controllers/api/v1/templates_controller.rb
- api/config/routes.rb
- ツアーテンプレート作成機能を追加
- https://github.com/e-harp-intern/R4FY/wiki/templates-create
- postmanとDBを確認
> #113 ツアーテンプレートの作成機能

- api/app/controllers/api/v1/tour_controller.rb
- api/app/mailers/tour_cancel_notify_mailer.rb
- api/app/views/tour_cancel_notify_mailer/cancel_email.text.erb
- ツアーを中止した際に、メールを送信するよう設定
- postmanで動作を確認
> #74 中止メールを送信する

- web/src/i18n/languages/ja.js
- web/src/views/tours/CreateTourView.vue
画面表示作るの面倒なので、とりあえずアラート出してます。
- 失敗時にアラートが表示されること。
> #154 ツアー作成画面で送信失敗時にアラートが出るように変更

- web/src/assets/css/style.css
- web/src/i18n/languages/ja.js
- web/src/views/accounts/GuideDetailView.vue
クリックでツアーに飛べるようにしました。
- 正しく表示できること
- クリックで指定のツアーへ移動できること
> #291 ガイド詳細画面に参加予定のツアー一覧を追加

- web/src/views/accounts/CreateAccountView.vue
- アカウントを新しく作成した際に、アカウント一覧画面へ移動すること
> #314 アカウント新規作成後にアカウント一覧画面へ移動するように変更

- web/src/views/tours/CreateTourView.vue
- ツアーを新しく作成した後に、自動的に作成したツアーの詳細画面へ移動すること
> #135 ツアー新規作成後に作成したツアーの詳細画面へ移動するよう変更

- web/src/i18n/languages/ja.js
- web/src/views/ToursListView.vue
> #238 ツアー一覧画面にIDを表示

- web/src/router/index.js
ページ名とファイル名をそろえました。
- コンソール上に警告が表示されないこと
-
> #283 ページ名の重複を修正

- api/app/controllers/api/v1/password_controller.rb
- api/app/controllers/api/v1/password_reset_controller.rb
- api/config/routes.rb
よく考えたらログインできないのでIDわかりませんね。
- メールが送信されること
> #306 パスワードの再設定に必要な情報を変更

- api/app/controllers/api/v1/guide_schedules_controller.rb
- 入力期限が過ぎていると予定が入力できないよう変更
- postmanとDBで確認
> #224 入力期限が過ぎると入力できないよう変更

- web/src/views/accounts/CreateAccountView.vue
> #319 アカウント作成成功時にダイアログを表示

- web/src/views/accounts/GuideDetailView.vue
> #326 ガイド詳細画面の削除済みフラグを修正

- api/app/controllers/api/v1/sessions_controller.rb
> #321 ログイン機能の不要な行を削除

- api/app/controllers/front_controller.rb
- web/src/i18n/languages/ja.js
- web/src/router/index.js
- web/src/views/PasswordResetView.vue
> #137 パスワード再設定画面の作成

- api/app/controllers/api/v1/tour_controller.rb
- api/config/routes.rb
- ツアー情報を更新するための機能です
- https://github.com/e-harp-intern/R4FY/wiki/tour-update
- postmanとDBで動作を確認
> #244 ツアー情報を更新するAPI

- api/app/controllers/api/v1/admins_controller.rb
- api/app/controllers/api/v1/guides_controller.rb
- api/config/routes.rb
> #279 deleteメソッドをdestroyに変更

- api/app/controllers/front_controller.rb
> #333 検証環境でパスワード再設定ページを開くことができるように修正

- api/app/controllers/api/v1/guide_schedules_controller.rb
- 中止されたツアーの予定を、ガイドが入力できないよう変更
- DBで変更されないことを確認
> #271 中止済みのツアーの予定を入力不可に

- api/app/controllers/api/v1/tour_controller.rb
> #339 メール送信より先にDBを更新

- web/src/views/LoginView.vue
- text から password に変更
- 実際のwebページで表示が変更されていること、ログインできることを確認
> #201 パスワード入力用のテキストボックスに変更

- web/src/components/SideMenu.vue
- web/src/i18n/languages/ja.js
- web/src/router/index.js
- web/src/views/accounts/MyAccountView.vue
パスワード変更ボタンは機能はつけていない。
ボタンを作成しただけ。
> #264 マイアカウント情報画面作成

- web/src/views/tours/TourDetailView.vue
- ツアー詳細画面の参加者一覧から各ガイドの詳細へ移動できること
> #302 ツアー詳細画面からガイドの詳細へ移動できるように設定

- api/db/migrate/20220916112558_rename_datetime_column_to_time_templates.rb
- api/db/schema.rb
`docker-compose run api rails db:migrate` をお願いします。
- ツアーテンプレートのDBの型・名前が変わったこと。
> #234 ツアーテンプレートの日時の型を時間に変更

- web/src/mixins/api.js
> #361 GETリクエストで配列を扱えるように修正

- web/src/assets/css/color.css
- web/src/views/ToursListView.vue
- web/src/views/tours/TourDetailView.vue
--color-tour-state-code-incomplete
--color-tour-state-code-assigned
--color-tour-state-code-complete
--color-tour-state-code-complete-recorded
--color-tour-state-code-cancel
ツアー一覧画面
ツアー詳細画面
を変更した
> #357 ツアー状態の色を変更

- api/app/controllers/api/v1/tour_schedules_mailer_controller.rb
- api/app/controllers/api/v1/tours_controller.rb
- api/app/controllers/concerns/schedule.rb
> #366 ツアー作成時にメールエラーが発生する問題を修正

- api/app/controllers/api/v1/tour_controller.rb
> #383 ツアー詳細取得APIで見つからなかった場合にエラーを返すよう修正

- web/src/mixins/common.js
- web/src/mixins/constant.js
- web/src/views/tours/TourDetailView.vue
> #360 ツアー詳細で取得エラーが発生した場合にエラーページへジャンプするよう変更

- web/src/i18n/languages/ja.js
- web/src/mixins/common.js
- web/src/views/tours/CreateTourView.vue
> #378 ツアー作成画面の開始終了日時のデフォルト値を設定

- api/app/controllers/api/v1/achievements_controller.rb
- api/app/controllers/api/v1/tour_guides_controller.rb
- web/src/views/tours/TourDetailView.vue
> #354 ツアー状態を戻す機能を修正削除

- web/src/i18n/languages/ja.js
- web/src/views/tours/CreateTourView.vue
> #245 ツアー作成画面で非必須パラメータを入力せずに作成できるように変更

- web/src/mixins/common.js
共通処理を変えています。他の箇所での影響は全て確認できていません。
> #396 文字列の状態で時差情報を削除するよう修正

- api/app/controllers/api/v1/admins_controller.rb
- api/app/controllers/api/v1/guide_schedules_controller.rb
- api/app/controllers/api/v1/guides_controller.rb
- api/app/controllers/api/v1/password_controller.rb
- api/app/controllers/api/v1/password_reset_controller.rb
- api/app/controllers/api/v1/sessions_controller.rb
- api/app/controllers/api/v1/tour_controller.rb
- api/app/models/admin.rb
一部機能で、書いているファイルがおかしいものがありましたが、動作はするのでとりあえずそのままにします。
> #382 トランザクションまわりの設定

- api/app/controllers/api/v1/tours_controller.rb
> #373 ツアー作成時のメール送信フラグを追加

- web/src/i18n/languages/ja.js
- web/src/router/index.js
- web/src/views/accounts/ChangePasswordView.vue
- web/src/views/accounts/MyAccountView.vue
PasswordResetViewと同じように実装しました。
@TomSuzuki 
変更後は、ログイン画面に戻らない方がいいですか？
このままで大丈夫でしょうか？
> パスワード変更画面及び機能作成

- web/src/views/tours/TourDetailView.vue
> #409 ツアー詳細画面のツアー操作の場所を変更

- web/src/i18n/languages/ja.js
- web/src/views/tours/TourDetailView.vue
> #368 ツアー詳細画面に担当者一覧を追加

- web/src/i18n/languages/ja.js
- web/src/mixins/constant.js
- web/src/views/tours/TourDetailView.vue
> #223 ツアー詳細画面の操作項目表示を状態によって変更

- api/app/controllers/api/v1/tour_controller.rb
- api/app/controllers/api/v1/tours_controller.rb
- api/db/migrate/20220829040520_create_tours.rb
- api/db/migrate/20220921160032_remove_column_tours.rb
- api/db/schema.rb
- api/db/seeds.rb
- web/src/i18n/languages/ja.js
- web/src/views/tours/CreateTourView.vue
- web/src/views/tours/EditTourView.vue
> #437 リマインド周りを変更

- api/app/controllers/api/v1/tour_complete_controller.rb
- api/config/routes.rb
- web/src/i18n/languages/ja.js
- web/src/views/tours/TourDetailView.vue
[tour complete · e-harp-intern/R4FY Wiki](https://github.com/e-harp-intern/R4FY/wiki/tour-complete)
> #442 ツアー実施済み強制変更

- api/app/controllers/concerns/achievement.rb
> #443 ガイドの参加したツアーの条件を変更

- api/app/controllers/api/v1/guide_schedules_controller.rb
- api/db/migrate/20220921165312_change_column_tours.rb
- api/db/schema.rb
- api/db/seeds.rb
- web/src/i18n/languages/ja.js
- web/src/views/tours/CreateTourView.vue
- web/src/views/tours/EditTourView.vue
> #440 予定入力期限を日時から日付に変更

- api/config/cronotab.rb
- api/lib/tasks/remind_notify.rake
（実行内容は仮のためコメントアウトしてます、rails g mailer RemindNotifyMailerしてないです）
> #103 バッチ処理の大枠作成

- api/db/migrate/20220829040520_create_tours.rb
- api/lib/tasks/remind_notify.rake
> #449 マイグレーション関連修正

- api/config/initializers/hosts.rb
- api/env.tmp
- build.sh
- docs/初回起動手順.md
- docs/検証環境手順.md
- web/.env.local.tmp
- web/package.json
- web/src/mixins/api.js
- web/src/router/index.js
- web/vue.config.js
> #454 設定の移動

- web/src/assets/css/style.css
- web/src/views/AccountsListView.vue
- web/src/views/ToursListView.vue
- web/src/views/accounts/MyAccountView.vue
> #461 共通パーツを使用していないボタンを修正

- web/src/views/accounts/GuideDetailView.vue
> #463 ガイド詳細画面のダミーボタンを削除

- web/src/views/tours/CreateTourView.vue
> #466 ツアー作成時のリマインド初期値を変更

- web/src/views/tours/SelectGuidesView.vue
> #456 担当ガイド決定画面のボタンの位置を修正

- web/src/views/AccountsListView.vue
> #459 アカウント一覧のボタンの初期値を変更

- web/src/views/accounts/CreateAccountView.vue
> #473 アカウント作成画面のラベルにforを設定

- web/src/views/guide/InputScheduleView.vue
> #476 ガイド予定入力画面で初期値として前回入力値を反映しない問題を修正

- web/src/i18n/languages/ja.js
- web/src/views/tours/TourDetailView.vue
> #432 ツアー詳細画面に足りない情報を追加

- web/src/assets/css/table.scss
- web/src/i18n/languages/ja.js
- web/src/views/tours/TourDetailView.vue
> #126 ツアー詳細画面で管理者側からガイドの予定を強制的に変更するボタンを追加

- web/src/components/LoadingTemplate.vue
> #485 ロードアニメーションのレイアウトを修正

- api/app/controllers/api/v1/tour_schedules_controller.rb
- api/app/controllers/api/v1/tours_controller.rb
- web/src/i18n/languages/ja.js
- web/src/views/tours/TourDetailView.vue
> #293 ガイドへ予定入力依頼を再送

- web/src/components/PageFooter.vue
- web/src/components/SideMenu.vue
- web/src/i18n/languages/ja.js
- web/src/mixins/common.js
- web/src/views/ToursListView.vue
- web/src/views/accounts/CreateAccountView.vue
- web/src/views/accounts/EditMyaccountInfoView.vue
- web/src/views/accounts/EditPasswordView.vue
- web/src/views/guide/InputScheduleView.vue
- web/src/views/tours/CreateTourView.vue
- web/src/views/tours/EditTourView.vue
- web/src/views/tours/SelectGuidesView.vue
- web/src/views/tours/TourDetailView.vue
> #462 日本語の修正

- web/src/assets/css/color.css
- web/src/assets/css/style.css
- web/src/i18n/languages/ja.js
- web/src/views/tours/SelectGuidesView.vue
- web/src/views/tours/TourDetailView.vue
> #491 デザインの微調整

- api/app/controllers/concerns/achievement.rb
- web/src/components/ToursTable.vue
- web/src/i18n/languages/ja.js
- web/src/views/ToursListView.vue
- web/src/views/accounts/GuideDetailView.vue
- web/src/views/tours/TourDetailView.vue
> #492 ガイド詳細の取得条件を変更

- web/src/router/index.js
[Vue で scrollBehavior が効かないときの対処法 - Qiita](https://qiita.com/gyuta/items/9dbf23d63f84f8cf2f5f)
> #488 ページ遷移時にスクロール位置が一番上になるよう修正

- web/src/assets/css/style.css
- web/src/components/layout/SimpleLayout.vue
- web/src/views/LoginView.vue
- web/src/views/ToursListView.vue
- web/src/views/guide/InputScheduleView.vue
> #498 エラーとなる画面の修正

- web/src/i18n/languages/ja.js
- web/src/views/guide/InputScheduleView.vue
> #497 仮の予定入力PC版

- api/app/mailers/remind_notify_mailer.rb
- api/app/views/remind_notify_mailer/creation_email.text.erb
- api/config/cronotab.rb
- api/lib/tasks/remind_notify.rake
> #76 リマインドメールの送信

- api/app/controllers/api/v1/tour_controller.rb
- web/src/views/tours/EditTourView.vue
> #495 ツアー編集にメモ編集機能を追加

- web/src/views/tours/SelectGuidesView.vue
> #508 ツアー担当者決定画面のメモで最後に担当したツアーが正しく表示されるように修正

- web/src/components/ToursTable.vue
> #507 ツアー一覧の状態表示で色が当たっていない問題を修正

- docs/初回起動手順.md
> #524 初回起動手順に設定の書き方を追加

- web/src/views/tours/SelectGuidesView.vue
> #516 担当ガイド決定画面で選択済みのカウント方法を変更

- api/app/controllers/front_controller.rb
> #518 未ログイン時のリダイレクト先を変更

- api/app/controllers/api/v1/guide_schedules_change_controller.rb
- api/app/controllers/api/v1/tours_controller.rb
- api/config/routes.rb
- web/src/views/tours/TourDetailView.vue
> #553 ガイドの参加可否を強制的に変更する際一括で変更するようにAPIを追加

- api/lib/tasks/remind_notify.rake
> #561 リマインドメールが送信されないツアーがある問題を修正

- api/app/controllers/api/v1/tour_controller.rb
- web/src/i18n/languages/ja.js
- web/src/views/tours/TourDetailView.vue
> #559 ツアー中止時のメール送信有無の選択を追加

- LICENSE
> #548 ライセンスファイルの追加

- api/app/controllers/api/v1/tours_controller.rb
- web/src/views/ToursListView.vue
> #558 ツアー一覧APIの初期値から中止を除くように変更
