api/app/controllers/api/v1/tourdetail_controller.rb
api/app/models/guide_schedule.rb
api/app/models/tour_guide.rb

`render` で返す際にネストした hash は設定しないとネスト部分が無視されるようなので、一度文字列にした後、もう一度Hash化しています（無駄な部分なので後で修正したい）。
- Modelで関連付けの設定が必要でした。
- [Active Record の関連付け - Railsガイド](https://railsguides.jp/association_basics.html)
- ツアー詳細取得時に、ガイド情報が紐づけられ、レスポンスにガイド情報が含まれること

#46 ツアー詳細にツアー情報を紐づけるよう変更

---

api/app/controllers/api/v1/tour_guides_controller.rb
api/config/routes.rb

ツアー担当ガイドを指定するためのAPIを作成しました。確認をお願いいたします。
- https://github.com/e-harp-intern/R4FY/wiki/tour-id-guides-post
- 存在するガイドを担当者として割り当て、担当を割り当てることができること
- ツアー状態コードを、担当者決定済みに変更できること
- [【Rails】 updateメソッドの使い方を徹底解説！ | Pikawaka](https://pikawaka.com/rails/update)

#67 ツアー担当ガイドの設定用APIを作成

---

api/app/models/tour.rb

ツアー時刻のバリデーションを設定しました
- ツアー作成時に終了時刻より前の開始時刻を設定すると、正しく登録できること
- ツアー作成時に終了時刻より後の開始時刻を設定すると、エラーとなること

#89 ツアー終了時刻のバリデーションを追加

---

api/app/controllers/api/v1/tours_controller.rb

ツアー一覧取得時に検索条件を指定できるようにしました。デフォルトの条件は #105 と [tours · e-harp-intern/R4FY Wiki](https://github.com/e-harp-intern/R4FY/wiki/tours) に記載しています。
- 指定した単語を含むツアーを検索できること
- 検索条件が正しく動くこと
- 開始日・終了日を設定できること
- ツアー状態で検索できること
- デフォルト値が意図したとおりに動作すること

#105 ツアー一覧取得APIに検索条件を追加

---

api/app/controllers/api/v1/achievements_controller.rb
api/config/routes.rb

- ガイドの実績を登録するAPIを作成。当初の指定URLは`localhost:3000/api/v1/tours/[tour_id]/achievements/[guide_id]`だったが、新しくファイルを作成したため`localhost:3000/api/v1/achievements/[tour_id]/achievements/[guide_id]`に変更している
- postmanでの出力とDBのデータが変更されていることを確認

#122 ガイドの実績を登録するAPIを作成

---

api/app/controllers/api/v1/guide_schedules_controller.rb
api/app/controllers/front_controller.rb

検証環境で、ガイドの予定入力時にページを開くことができるように。

#198 トークンでページを開くことができるようにページコントローラーに機能を追加

---

web/src/App.vue

ページ名がついていない場合は何もないレイアウトを表示させるように変更しました。

#206 ページ読み込み時にデフォルトレイアウトのメニューが一瞬見える問題を修正

---

api/app/controllers/api/v1/tour_achievements_controller.rb
api/app/controllers/concerns/achievement.rb
api/config/routes.rb

#175 ツアー単位で予定入力を求めたガイドの実績情報をすべて取得するAPIの作成

---

api/app/controllers/api/v1/admins_controller.rb
api/config/routes.rb

- #96を強化。/meの場合、今回のissueで指定された形で従来通りに表示。それ以外の場合、IDで検索して表示
- https://github.com/e-harp-intern/R4FY/wiki/admins-me
- https://github.com/e-harp-intern/R4FY/wiki/admins-index
- postmanで正しく表示されることを確認

#241 管理者詳細を取得

---

docs/初回起動手順.md

説明を追加しました。設定が追加されたので、未設定の方は設定を追記後、`docker-compose stop`, `docker-compose up`で再起動してください。

#253 初回起動手順にSERVER_PATHの設定を追加

---

api/app/controllers/api/v1/guides_controller.rb

- ガイドアカウントの論理削除時に紐づいたトークンも削除する
- wikiの更新もしました
- https://github.com/e-harp-intern/R4FY/wiki/guides-delete
- DBで削除されたことを確認

#199 ガイドアカウントの論理削除時にtokenも削除するAPI

---

web/src/views/tours/TourDetailView.vue

ごめんなさい。消してました。
- ツアー詳細画面でツアー名が正しく表示されること

#292 ツアー詳細画面のタイトルのCSSが消えていたので修正

---

web/src/i18n/languages/ja.js
web/src/views/accounts/GuideDetailView.vue

内部的にエラーが出ていますが、時間がある時にやります。
- 論理削除済みユーザーの詳細ページを開いた際にエラーメッセージを表示すること

#299 ガイド詳細画面で論理削除済みユーザーを開こうとしたときにエラーとなる問題を修正

---

api/app/controllers/api/v1/accounts_controller.rb

wiki更新済み → [accounts · e-harp-intern/R4FY Wiki](https://github.com/e-harp-intern/R4FY/wiki/accounts)
- デフォルトで論理削除済みユーザーを除外すること
- `include_invalid` が `true` で論理削除済みユーザーを含むこと
- `include_invalid` が `false` で論理削除済みユーザーを含まないこと

#300 アカウント一覧APIのデフォルトパラメータを論理削除済みユーザーを除外する設定に変更

---

web/src/views/tours/SelectGuidesView.vue

- 担当者決定画面で、すでに担当になっているガイドのチェックボックスに初期値としてチェックが入ること
- チェックの切り替えができること

#230 担当者決定画面で担当者が決まっている場合に初期値を反映

---

web/src/views/tours/TourDetailView.vue

- 中止処理を非同期実行していたことが原因でした。
- サーバーに負荷がかかっていると、中止処理よりも先に取得処理が行われ、更新されていないように見えているだけでした。
- マージ後再度検証環境で動作確認

#320 ツアー中止時に画面に反映されないことがある問題を修正

---

api/app/models/tour.rb

- ツアー作成時に負の人数でエラーとなること
- [Railsで「整数のみ」、「０以上の正の数のみ」のvalidatesの書き方 - Qiita](https://qiita.com/syohhe/items/ecef500da2cd7956489d)

#317 マイナスの人数を登録できないようにバリデーションを追加

---

api/app/controllers/api/v1/achievements_controller.rb
api/app/controllers/api/v1/guide_schedules_controller.rb

- 実績入力時、参加したガイド全員が実績入力済ではなかった場合、ツアー状態コードを変更する機能
- DBで正しく変更されることを確認

#227 実績入力時にツアー状態コードを変更するAPI

---

api/app/controllers/api/v1/tour_schedules_controller.rb
api/config/routes.rb

- 予定作成メールを再送する機能を追加
- https://github.com/e-harp-intern/R4FY/wiki/tour_schedule-create
- postmanとmailを確認

#286 予定作成メールの再送機能

---

api/app/controllers/api/v1/tour_guides_controller.rb
api/app/mailers/assign_cancel_notify_mailer.rb
api/app/views/assign_cancel_notify_mailer/cancel_email.text.erb

- 担当ガイドをリセットした際に、担当者全員に通知メールが行くよう設定
- wikiの更新 https://github.com/e-harp-intern/R4FY/wiki/tour-id-guides-delete
- mailを確認

#236 担当ガイド取り消しメール

---

api/app/controllers/api/v1/tour_guides_controller.rb

- 担当ガイド割り当てフラグを追加。初期値はtrueで、falseになった場合、メールを送信しない。
- wikiの更新 https://github.com/e-harp-intern/R4FY/wiki/tour-id-guides-post
- mailを確認

#232 担当ガイド割り当てメール送信フラグを追加

---

api/app/controllers/api/v1/tours_controller.rb

- 子供大人ガイドのパラメータの初期値を０にする
- ツアー作成時、子供大人ガイドが無記入・空文字であれば０にする。

#345 ツアー作成APIの子供大人ガイドを任意の数とする

---

api/app/controllers/api/v1/guide_schedules_controller.rb

- ガイド側で予定入力・確認を行ったとき、ツアーが開始済みの場合と担当者が決定済みの場合に制限がかかるよう設定
- postmanで確認

#343 ガイド側の予定入力・確認に制限

---

web/src/views/tours/TourDetailView.vue

テーブルや並び替え周りでエラーが発生するのですが、原因はツアー状態によってテーブルの色を変える機能でした。
`tour`が更新されていないにもかかわらず、`changeToTourStateColor`が再実行？され、`document.getElementById("state")`で要素の取得ができないため`obj`が`null`となってしまい、`obj.id`にアクセスできないことが理由のようです。
- ツアー詳細画面で参加者の並び替えができること。
- ツアー詳細画面でツアー状態に応じてテーブルの色が変わること。

#213 ツアー詳細画面で参加者を並び替えるとエラーが発生する問題を修正

---

web/src/views/PasswordResetView.vue

オートフォーマットに`return`を消されたことが原因でした。

#365 パスワード再設定画面でパスワードが違う場合に再設定を行なわないように修正

---

web/src/i18n/languages/ja.js
web/src/views/tours/SelectGuidesView.vue

表に追加することが難しいので、別タブで情報を開く仕様にしました。

#174 担当ガイド決定画面からガイド情報画面へのリンクを追加

---

api/app/controllers/api/v1/tour_guides_controller.rb
api/app/mailers/not_assign_mailer.rb
api/app/views/not_assign_mailer/creation_email.text.erb

- 設定が正しく行われる
- 初回のみ「割り当たらなかったメール」を送信する
- 新しく割り当てられたガイドに「割り当てメール」を送信する
- 割り当てから外れたガイドに「担当から外れたメール」を送信する

#231 担当ガイド割り当て時の挙動を修正

---

web/src/views/tours/CreateTourView.vue

#410 ツアー追加画面の初期日時がずれている問題を修正

---

api/app/controllers/api/v1/tour_guides_controller.rb

[[Rails]POSTで送ったboolean値がおかしかった原因 - Qiita](https://qiita.com/chocode/items/e00435abac0bc459f0e6) デフォルト値処理が原因でした。

#425 ツアーガイド決定APIのメール送信有無パラメータが正しく処理されるよう修正

---

web/src/mixins/table.js
web/src/views/ToursListView.vue

並び替えキーに`null`を指定した場合に、前回並び替え時と同じ条件で並び変わるようにしました。

#424 ツアー一覧で検索時に並び替え条件を保持

---

web/src/views/tours/TourDetailView.vue

#471 CSSの名前かぶりを修正

---

web/src/components/GuidesTable.vue
web/src/views/tours/SelectGuidesView.vue

#570 担当ガイド決定画面でグレーアウトのガイドを選択できないように修正
